// frontend/src/components/PropertyCard.vue
<template>
  <div class="property-card" @click="$router.push(`/detail/${property.id}`)">
    <!-- 图片 -->
    <div class="card-image">
      <van-image
        :src="property.images?.[0] || 'https://via.placeholder.com/400x250/667eea/ffffff?text=CM'"
        fit="cover"
        height="200"
        loading="lazy"
      />
      <div class="card-badges">
        <van-tag :color="property.price_type === 'rent' ? '#ee0a24' : '#07c160'" size="medium">
          {{ property.price_type === 'rent' ? '出租' : '出售' }}
        </van-tag>
        <van-tag color="#1989fa" size="medium" v-if="property.furnished">精装修</van-tag>
      </div>
    </div>

    <!-- 内容 -->
    <div class="card-body">
      <div class="card-price">
        <span class="price-amount">฿{{ formattedPrice }}</span>
        <span class="price-unit">{{ property.price_type === 'rent' ? '/月' : '' }}</span>
      </div>
      <div class="card-title van-multi-ellipsis--l2">{{ property.title }}</div>
      <div class="card-info">
        <span>{{ property.bedrooms }}卧{{ property.bathrooms }}卫</span>
        <span class="dot">·</span>
        <span>{{ property.area_sqm }}m²</span>
        <span class="dot">·</span>
        <span>{{ property.district }}</span>
      </div>
      <div class="card-footer">
        <span class="card-source">{{ property.source_label || property.source }}</span>
        <div class="card-actions">
          <van-icon
            :name="isFav ? 'star' : 'star-o'"
            :color="isFav ? '#ee0a24' : '#999'"
            size="18"
            @click.stop="toggleFav"
          />
          <van-icon
            :name="inCompare ? 'smile-o' : 'smile-comment-o'"
            color="#999"
            size="18"
            style="margin-left:12px"
            @click.stop="toggleCompare"
          />
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { computed } from 'vue'
import { useRouter } from 'vue-router'
import { usePropertyStore } from '@/stores/property'
import { useCompareStore } from '@/stores/compare'

const props = defineProps({
  property: { type: Object, required: true }
})

const router = useRouter()
const store = usePropertyStore()
const compareStore = useCompareStore()

const formattedPrice = computed(() => {
  const p = store.getPriceValue(props.property)
  if (!p) return '0'
  if (p >= 10000) return (p / 10000).toFixed(1) + '万'
  return p.toLocaleString()
})

const isFav = computed(() => store.isFavorite(props.property.id))
const inCompare = computed(() => compareStore.hasItem(props.property.id))

function toggleFav() {
  store.toggleFavorite(props.property)
}

function toggleCompare() {
  if (inCompare.value) {
    compareStore.removeItem(props.property.id)
  } else {
    compareStore.addItem(structuredClone(props.property))
  }
}
</script>

<style scoped>
.property-card {
  background: #fff;
  border-radius: 12px;
  overflow: hidden;
  box-shadow: 0 2px 12px rgba(0,0,0,0.06);
  transition: transform 0.2s;
}
.property-card:active {
  transform: scale(0.98);
}
.card-image {
  position: relative;
}
.card-badges {
  position: absolute;
  top: 10px;
  left: 10px;
  display: flex;
  gap: 6px;
}
.card-body {
  padding: 12px 14px 14px;
}
.card-price {
  margin-bottom: 6px;
}
.price-amount {
  font-size: 20px;
  font-weight: 700;
  color: #ee0a24;
}
.price-unit {
  font-size: 13px;
  color: #999;
}
.card-title {
  font-size: 14px;
  font-weight: 500;
  color: #333;
  line-height: 1.4;
  margin-bottom: 6px;
}
.card-info {
  font-size: 13px;
  color: #888;
  margin-bottom: 10px;
}
.dot {
  margin: 0 4px;
  color: #ccc;
}
.card-footer {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding-top: 8px;
  border-top: 1px solid #f5f5f5;
}
.card-source {
  font-size: 12px;
  color: #aaa;
}
.card-actions {
  display: flex;
  align-items: center;
}
</style>

// frontend-react/src/components/PropertyCard.jsx
import React from 'react'
import { useNavigate } from 'react-router-dom'
import usePropertyStore from '../stores/propertyStore'
import useCompareStore from '../stores/compareStore'

export default function PropertyCard({ property, showActions = true }) {
  const navigate = useNavigate()
  const toggleFavorite = usePropertyStore((s) => s.toggleFavorite)
  const isFavorite = usePropertyStore((s) => s.isFavorite)
  const getPriceValue = usePropertyStore((s) => s.getPriceValue)
  const addItem = useCompareStore((s) => s.addItem)
  const removeItem = useCompareStore((s) => s.removeItem)
  const hasItem = useCompareStore((s) => s.hasItem)
  const compareCount = useCompareStore((s) => s.count)

  const price = getPriceValue(property)
  const isRent = property.price_type === 'RENT'
  const fav = isFavorite(property.id)
  const inCompare = hasItem(property.id)

  const formatPrice = (val) => {
    if (!val) return ''
    if (val >= 10000) return `${(val / 10000).toFixed(1)}万`
    return val.toLocaleString()
  }

  const typeLabel = property.property_type
    ? { CONDO: '公寓', HOUSE: '别墅', TOWNHOUSE: '联排', APARTMENT: '普通公寓' }[property.property_type] || property.property_type
    : ''

  return (
    <div className="property-card" onClick={() => navigate(`/detail/${property.id}`)}>
      <img
        className="property-card-img"
        src={property.images?.[0] || 'https://via.placeholder.com/400x280/667eea/ffffff?text=CM'}
        alt={property.title}
        loading="lazy"
      />
      <div className="property-card-body">
        <div className={`property-card-price ${!isRent ? 'sale' : ''}`}>
          {price ? `฿${formatPrice(price)}` : '面议'}
          <span className="property-card-price-unit">{isRent ? '/月' : '（总价）'}</span>
        </div>
        <div className="property-card-title">{property.title || '房产标题'}</div>
        <div className="property-card-meta">
          <span>🛏 {property.bedrooms || '-'}室</span>
          <span>🚿 {property.bathrooms || '-'}卫</span>
          <span>📐 {property.area_sqm || '-'}m²</span>
          {typeLabel && <span>{typeLabel}</span>}
        </div>
        <div className="property-card-footer">
          <span className="property-card-source">{property.source || '未知来源'}</span>
          {showActions && (
            <div className="property-card-actions">
              <span
                style={{ cursor: 'pointer', fontSize: '16px', color: fav ? '#ee0a24' : '#ccc' }}
                onClick={(e) => { e.stopPropagation(); toggleFavorite(property) }}
              >
                {fav ? '❤️' : '🤍'}
              </span>
              <span
                style={{ cursor: 'pointer', fontSize: '16px', color: inCompare ? '#1989fa' : '#ccc' }}
                onClick={(e) => {
                  e.stopPropagation()
                  inCompare ? removeItem(property.id) : addItem({ ...property })
                }}
              >
                📊
              </span>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
